/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:textdraw_0[MAX_PLAYERS];
new PlayerText:textdraw_1[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new PlayerText:textdraw_3[MAX_PLAYERS];
new PlayerText:textdraw_4[MAX_PLAYERS];
new PlayerText:textdraw_5[MAX_PLAYERS];
new PlayerText:textdraw_6[MAX_PLAYERS];
new PlayerText:textdraw_7[MAX_PLAYERS];
new PlayerText:textdraw_8[MAX_PLAYERS];
new PlayerText:textdraw_9[MAX_PLAYERS];

//Textdraws
//Player Textdraws
textdraw_0[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 114.000000, "_");
PlayerTextDrawFont(playerid, textdraw_0[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_0[playerid], 1.216665, 14.600060);
PlayerTextDrawTextSize(playerid, textdraw_0[playerid], 412.000000, 24.500000);
PlayerTextDrawSetOutline(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetShadow(playerid, textdraw_0[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_0[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_0[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_0[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_0[playerid], 160);
PlayerTextDrawUseBox(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_0[playerid], 0);

textdraw_1[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 114.000000, "CALL OF DUTY WARZONE RULES");
PlayerTextDrawFont(playerid, textdraw_1[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_1[playerid], 0.237498, 1.250000);
PlayerTextDrawTextSize(playerid, textdraw_1[playerid], 397.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_1[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_1[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_1[playerid], -16776961);
PlayerTextDrawBackgroundColor(playerid, textdraw_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_1[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_1[playerid], 0);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 129.000000, "- Earn money with your teammates on the battlefield (check map to see location)");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 0);

textdraw_3[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 148.000000, "- Airdrops are deployed, try to check it out it's worth it ! But be careful ...");
PlayerTextDrawFont(playerid, textdraw_3[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_3[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_3[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_3[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_3[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_3[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_3[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_3[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_3[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_3[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_3[playerid], 0);

textdraw_4[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 168.000000, "- /flare or N to use a flare. You will respawn in the sky at your next deployment, it can be destroyed !");
PlayerTextDrawFont(playerid, textdraw_4[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_4[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_4[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_4[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_4[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_4[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_4[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_4[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_4[playerid], 0);

textdraw_5[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 189.000000, "- /revive to revive a player");
PlayerTextDrawFont(playerid, textdraw_5[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_5[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_5[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_5[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_5[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_5[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_5[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_5[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_5[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_5[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_5[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_5[playerid], 0);

textdraw_6[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 201.000000, "- CHEATING ON THE SERVER WILL BE PUNISHED");
PlayerTextDrawFont(playerid, textdraw_6[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_6[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_6[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_6[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_6[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_6[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_6[playerid], -16776961);
PlayerTextDrawBackgroundColor(playerid, textdraw_6[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_6[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_6[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_6[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_6[playerid], 0);

textdraw_7[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 212.000000, "- Everyone has the same loadout");
PlayerTextDrawFont(playerid, textdraw_7[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_7[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_7[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_7[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_7[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_7[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_7[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_7[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_7[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_7[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_7[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_7[playerid], 0);

textdraw_8[playerid] = CreatePlayerTextDraw(playerid, 212.000000, 223.000000, "- FAST GAMEPLAY, FAST GAME, PLEASE ENJOY AND SHARE TO YOUR FRIENDS");
PlayerTextDrawFont(playerid, textdraw_8[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_8[playerid], 0.170833, 1.049998);
PlayerTextDrawTextSize(playerid, textdraw_8[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_8[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_8[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_8[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_8[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_8[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_8[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_8[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_8[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_8[playerid], 0);

textdraw_9[playerid] = CreatePlayerTextDraw(playerid, 402.000000, 114.000000, "X");
PlayerTextDrawFont(playerid, textdraw_9[playerid], 1);
PlayerTextDrawLetterSize(playerid, textdraw_9[playerid], 0.408333, 1.149999);
PlayerTextDrawTextSize(playerid, textdraw_9[playerid], 412.000000, 23.500000);
PlayerTextDrawSetOutline(playerid, textdraw_9[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_9[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_9[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_9[playerid], -16776961);
PlayerTextDrawBackgroundColor(playerid, textdraw_9[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_9[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_9[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_9[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_9[playerid], 1);

