/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new Text:textdraw_0;
new Text:textdraw_1;
new Text:textdraw_2;
new Text:textdraw_2;
new Text:textdraw_2;
new Text:textdraw_2;

//Textdraws
textdraw_0 = TextDrawCreate(557.000000, 86.000000, "~g~ANTI-TERRORISTS~n~~w~100/100");
TextDrawFont(textdraw_0, 3);
TextDrawLetterSize(textdraw_0, 0.224999, 1.100000);
TextDrawTextSize(textdraw_0, 617.000000, 17.000000);
TextDrawSetOutline(textdraw_0, 0);
TextDrawSetShadow(textdraw_0, 0);
TextDrawAlignment(textdraw_0, 1);
TextDrawColor(textdraw_0, -1);
TextDrawBackgroundColor(textdraw_0, -16776961);
TextDrawBoxColor(textdraw_0, -16777166);
TextDrawUseBox(textdraw_0, 1);
TextDrawSetProportional(textdraw_0, 1);
TextDrawSetSelectable(textdraw_0, 0);

textdraw_1 = TextDrawCreate(319.000000, 1.000000, "ID:_0_I_PING:_14_I_XP:_150/1840_I_LVL:_15_I_K:_64_I_D:_102");
TextDrawFont(textdraw_1, 2);
TextDrawLetterSize(textdraw_1, 0.279166, 1.350000);
TextDrawTextSize(textdraw_1, 12.000000, 640.000000);
TextDrawSetOutline(textdraw_1, 0);
TextDrawSetShadow(textdraw_1, 0);
TextDrawAlignment(textdraw_1, 2);
TextDrawColor(textdraw_1, -1);
TextDrawBackgroundColor(textdraw_1, 255);
TextDrawBoxColor(textdraw_1, 101);
TextDrawUseBox(textdraw_1, 1);
TextDrawSetProportional(textdraw_1, 1);
TextDrawSetSelectable(textdraw_1, 0);

textdraw_2 = TextDrawCreate(557.000000, 108.000000, "~y~AIRDROP:~w~ LANDED");
TextDrawFont(textdraw_2, 3);
TextDrawLetterSize(textdraw_2, 0.187500, 1.100000);
TextDrawTextSize(textdraw_2, 617.000000, 17.000000);
TextDrawSetOutline(textdraw_2, 0);
TextDrawSetShadow(textdraw_2, 0);
TextDrawAlignment(textdraw_2, 1);
TextDrawColor(textdraw_2, -1);
TextDrawBackgroundColor(textdraw_2, 255);
TextDrawBoxColor(textdraw_2, 50);
TextDrawUseBox(textdraw_2, 0);
TextDrawSetProportional(textdraw_2, 1);
TextDrawSetSelectable(textdraw_2, 0);

//Player Textdraws
