/*
This file was generated by Nickk's TextDraw editor script
Nickk888 is the author of the NTD script
*/

//Variables
new PlayerText:textdraw_0[MAX_PLAYERS];
new PlayerText:textdraw_1[MAX_PLAYERS];
new PlayerText:textdraw_2[MAX_PLAYERS];
new PlayerText:textdraw_3[MAX_PLAYERS];
new PlayerText:textdraw_4[MAX_PLAYERS];

//Textdraws
//Player Textdraws
textdraw_0[playerid] = CreatePlayerTextDraw(playerid, 257.000000, 122.000000, "TextDraw");
PlayerTextDrawFont(playerid, textdraw_0[playerid], 5);
PlayerTextDrawLetterSize(playerid, textdraw_0[playerid], 0.600000, 2.000000);
PlayerTextDrawTextSize(playerid, textdraw_0[playerid], 122.000000, 164.000000);
PlayerTextDrawSetOutline(playerid, textdraw_0[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_0[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_0[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_0[playerid], -1094795521);
PlayerTextDrawBackgroundColor(playerid, textdraw_0[playerid], -181);
PlayerTextDrawBoxColor(playerid, textdraw_0[playerid], 50);
PlayerTextDrawUseBox(playerid, textdraw_0[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_0[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_0[playerid], 0);
PlayerTextDrawSetPreviewModel(playerid, textdraw_0[playerid], 0);
PlayerTextDrawSetPreviewRot(playerid, textdraw_0[playerid], -10.000000, 0.000000, -20.000000, 1.000000);
PlayerTextDrawSetPreviewVehCol(playerid, textdraw_0[playerid], 1, 1);

textdraw_1[playerid] = CreatePlayerTextDraw(playerid, 350.000000, 287.000000, ">>");
PlayerTextDrawFont(playerid, textdraw_1[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_1[playerid], 0.466666, 1.750000);
PlayerTextDrawTextSize(playerid, textdraw_1[playerid], 378.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_1[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_1[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_1[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_1[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_1[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_1[playerid], -1094795726);
PlayerTextDrawUseBox(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_1[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_1[playerid], 1);

textdraw_2[playerid] = CreatePlayerTextDraw(playerid, 258.000000, 287.000000, "<<");
PlayerTextDrawFont(playerid, textdraw_2[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_2[playerid], 0.466666, 1.750000);
PlayerTextDrawTextSize(playerid, textdraw_2[playerid], 285.500000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_2[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_2[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_2[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_2[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_2[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_2[playerid], -1094795726);
PlayerTextDrawUseBox(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_2[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_2[playerid], 1);

textdraw_3[playerid] = CreatePlayerTextDraw(playerid, 287.500000, 287.000000, "SELECT");
PlayerTextDrawFont(playerid, textdraw_3[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_3[playerid], 0.404166, 1.700000);
PlayerTextDrawTextSize(playerid, textdraw_3[playerid], 348.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_3[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_3[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_3[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_3[playerid], -1);
PlayerTextDrawBackgroundColor(playerid, textdraw_3[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_3[playerid], -1094795726);
PlayerTextDrawUseBox(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetProportional(playerid, textdraw_3[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_3[playerid], 1);

textdraw_4[playerid] = CreatePlayerTextDraw(playerid, 366.000000, 123.000000, "X");
PlayerTextDrawFont(playerid, textdraw_4[playerid], 2);
PlayerTextDrawLetterSize(playerid, textdraw_4[playerid], 0.466666, 1.750000);
PlayerTextDrawTextSize(playerid, textdraw_4[playerid], 378.000000, 17.000000);
PlayerTextDrawSetOutline(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetShadow(playerid, textdraw_4[playerid], 0);
PlayerTextDrawAlignment(playerid, textdraw_4[playerid], 1);
PlayerTextDrawColor(playerid, textdraw_4[playerid], -16776961);
PlayerTextDrawBackgroundColor(playerid, textdraw_4[playerid], 255);
PlayerTextDrawBoxColor(playerid, textdraw_4[playerid], -1094795726);
PlayerTextDrawUseBox(playerid, textdraw_4[playerid], 0);
PlayerTextDrawSetProportional(playerid, textdraw_4[playerid], 1);
PlayerTextDrawSetSelectable(playerid, textdraw_4[playerid], 1);

